/*
 * Preview catalogue data for DLS Bathrooms Ltd.
 * Prices are public catalogue list-price guides including VAT and must be
 * confirmed before quotation or order. Supplier pages are retained per item
 * so the DLS back office can verify current details quickly.
 */
window.DLS_PRODUCTS = [
  {
    id: "belini-btw-pan",
    category: "Toilets & sanitaryware",
    roomGroup: "toilet",
    name: "Belini Rimless Back-to-Wall Pan",
    sku: "BELINI005",
    price: 300,
    finish: "Gloss White",
    dimensions: "365 W × 430 H × 510 D mm",
    features: ["Rimless design", "Back-to-wall", "Seat selected separately"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/BELINI005_CUTOUT_001-1500x1500.jpg",
    source: "https://www.scudo.co.uk/products/430mm-rimless-btw-pan/",
    tags: ["toilet", "wc", "pan", "rimless", "back to wall", "belini", "white"]
  },
  {
    id: "deia-comfort-btw-pan",
    category: "Toilets & sanitaryware",
    roomGroup: "toilet",
    name: "Deia Rimless Comfort Height Back-to-Wall Pan",
    sku: "DEIA010",
    price: 352,
    finish: "Gloss White",
    dimensions: "365 W × 455 H × 485 D mm",
    features: ["Comfort height", "Rimless design", "Seat selected separately"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/DEIA010_CUTOUT_001-1500x1500.jpg",
    source: "https://www.scudo.co.uk/products/455mm-rimless-comfort-height-btw-pan/",
    tags: ["toilet", "wc", "pan", "comfort height", "rimless", "back to wall", "deia"]
  },
  {
    id: "wc-frame-cistern",
    category: "Toilets & sanitaryware",
    roomGroup: "toilet",
    name: "WC Frame & Concealed Cistern",
    sku: "WC-FRAME002",
    price: 341,
    finish: "White / Grey",
    dimensions: "480 W × 1134–1464 H × 101 D mm",
    features: ["Adjustable height", "3/6 litre flush", "For wall-hung WC layouts"],
    image: null,
    source: "https://www.scudo.co.uk/products/wc-frame-cistern-with-chrome-flush-plate/",
    tags: ["wc frame", "cistern", "concealed", "wall hung", "toilet frame"]
  },
  {
    id: "black-flush-button",
    category: "Toilets & sanitaryware",
    roomGroup: "toilet",
    name: "Square Black Dual Flush Button",
    sku: "WC-BUTTON02",
    price: 89,
    finish: "Matte Black",
    dimensions: "236 W × 152 H × 9 D mm",
    features: ["Pneumatic", "Dual flush", "Compatible with WC-FRAME002"],
    image: null,
    source: "https://www.scudo.co.uk/products/square-black-dual-flush-button-2/",
    tags: ["flush button", "black", "wc button", "dual flush", "toilet"]
  },
  {
    id: "contactless-flush-sensor",
    category: "Toilets & sanitaryware",
    roomGroup: "toilet",
    name: "Contactless Flush Sensor",
    sku: "FLUSH-SENSOR",
    price: 106,
    finish: "White",
    dimensions: "79 W × 210 H mm",
    features: ["Battery powered", "Manual backup", "IPX4 rated"],
    image: null,
    source: "https://www.scudo.co.uk/products/contactless-flush-sensor/",
    tags: ["contactless", "flush", "sensor", "toilet", "wc"]
  },
  {
    id: "porto-basin",
    category: "Furniture & basins",
    roomGroup: "basin",
    name: "Porto Basin",
    sku: "PORTO003",
    price: 134,
    finish: "White Vitreous China",
    dimensions: "550 W × 200 H × 450 D mm",
    features: ["One tap hole", "Built-in overflow", "Pedestal required"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/PORTO003_CUTOUT_001-1.jpg",
    source: "https://www.scudo.co.uk/products/porto-basin-500mm/",
    tags: ["basin", "sink", "porto", "pedestal", "white", "550"]
  },
  {
    id: "bota-500-basin",
    category: "Furniture & basins",
    roomGroup: "basin",
    name: "Bota 500 Furniture Basin",
    sku: "BASIN017",
    price: 249,
    finish: "Gloss White",
    dimensions: "505 W × 50 H × 455 D mm",
    features: ["Furniture mounted", "One tap hole", "Bota cabinet required"],
    image: null,
    source: "https://www.scudo.co.uk/products/bota-500-basin-2/",
    tags: ["basin", "sink", "bota", "500", "furniture", "vanity"]
  },
  {
    id: "muro-600-basin",
    category: "Furniture & basins",
    roomGroup: "basin",
    name: "Muro 600 Furniture Basin",
    sku: "BASIN-615-365-CER",
    price: 175,
    finish: "White",
    dimensions: "610 W × 40 H × 365 D mm",
    features: ["Furniture mounted", "One tap hole", "Chrome overflow included"],
    image: null,
    source: "https://www.scudo.co.uk/products/muro-600-basin/",
    tags: ["basin", "sink", "muro", "600", "furniture", "vanity"]
  },
  {
    id: "lira-fluted-bath",
    category: "Baths",
    roomGroup: "bath",
    name: "Lira Oval Fluted Freestanding Bath",
    sku: "BATH-008",
    price: 2000,
    finish: "Gloss White",
    dimensions: "1700 L × 750 W × 580 H mm",
    features: ["Fluted exterior", "Slit overflow", "White pop-up included"],
    image: null,
    source: "https://www.scudo.co.uk/products/lira-oval-fluted-freestanding-bath/",
    tags: ["bath", "freestanding", "fluted", "lira", "1700", "oval"]
  },
  {
    id: "coral-bath",
    category: "Baths",
    roomGroup: "bath",
    name: "Coral Freestanding Bath",
    sku: "BATH-004",
    price: 2000,
    finish: "Gloss White",
    dimensions: "1700 L × 750 W × 570 H mm",
    features: ["Freestanding", "Slit overflow", "White pop-up included"],
    image: null,
    source: "https://www.scudo.co.uk/products/coral-freestanding-bath/",
    tags: ["bath", "freestanding", "coral", "1700", "oval"]
  },
  {
    id: "onyx-1655-bath",
    category: "Baths",
    roomGroup: "bath",
    name: "Onyx Freestanding Bath 1655",
    sku: "BATH-DE1655",
    price: 1785,
    finish: "Gloss White",
    dimensions: "1655 L × 745 W × 580 H mm",
    features: ["Central waste", "Waste and overflow included", "Double ended"],
    image: null,
    source: "https://www.scudo.co.uk/products/onyx-bath-in-acrylic-white-1655/",
    tags: ["bath", "freestanding", "onyx", "1655", "double ended"]
  },
  {
    id: "labyrinth-bath",
    category: "Baths",
    roomGroup: "bath",
    name: "Labyrinth Fluted Freestanding Bath",
    sku: "BATH-002",
    price: 2200,
    finish: "White",
    dimensions: "1700 L × 800 W × 590 H mm",
    features: ["Statement fluted edge", "Waste and overflow included", "Freestanding"],
    image: null,
    source: "https://www.scudo.co.uk/products/labyrinth-fluted-freestanding/",
    tags: ["bath", "freestanding", "labyrinth", "fluted", "1700"]
  },
  {
    id: "messi-riser-shower",
    category: "Showers",
    roomGroup: "shower",
    name: "Messi Round Cool Touch Rigid Riser Shower",
    sku: "SHOWER009",
    price: 352,
    finish: "Chrome",
    dimensions: "250 W × 870–1200 H × 330 D mm",
    features: ["Cool touch", "Thermostatic control", "Two outlets"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/SHOWER009.jpg",
    source: "https://www.scudo.co.uk/products/messi-cool-touch-round-bar-valve-adjustable-rigid-riser/",
    tags: ["shower", "rigid riser", "chrome", "thermostatic", "messi", "cool touch"]
  },
  {
    id: "core-nickel-riser",
    category: "Showers",
    roomGroup: "shower",
    name: "Core Round Rigid Riser Shower",
    sku: "NU-163",
    price: 578,
    finish: "Brushed Nickel",
    dimensions: "275 W × 854–1219 H mm",
    features: ["Thermostatic mixer", "WRAS approved", "Adjustable riser"],
    image: null,
    source: "https://www.scudo.co.uk/products/core-brushed-nickel-round-rigid-riser-shower/",
    tags: ["shower", "rigid riser", "brushed nickel", "thermostatic", "core"]
  },
  {
    id: "s8-brass-panel-800",
    category: "Screens & wetrooms",
    roomGroup: "screen",
    name: "S8 Brushed Brass Wetroom Panel 800",
    sku: "S8-WET800CHR",
    price: 357,
    finish: "Brushed Brass / Clear Glass",
    dimensions: "775–790 W × 2000 H mm",
    features: ["8 mm toughened glass", "Aqua-Shield treatment", "Frameless look"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/brass_wetrooom_panel.jpg",
    source: "https://www.scudo.co.uk/products/s8-brushed-brass-panel-800/",
    tags: ["wetroom", "screen", "panel", "brushed brass", "glass", "800"]
  },
  {
    id: "s6-brass-bath-screen",
    category: "Screens & wetrooms",
    roomGroup: "screen",
    name: "S6 Brushed Brass Radius Bath Screen",
    sku: "LS102BB",
    price: 194,
    finish: "Brushed Brass / Clear Glass",
    dimensions: "800 W × 1400 H mm",
    features: ["6 mm glass", "Inward and outward swing", "Semi-framed"],
    image: null,
    source: "https://www.scudo.co.uk/products/s6-brushed-brass-radius-bath-screen/",
    tags: ["bath screen", "screen", "brushed brass", "glass", "radius"]
  },
  {
    id: "s8-brass-profile-pack",
    category: "Screens & wetrooms",
    roomGroup: "screen",
    name: "S8 Brushed Brass Wetroom Profile Pack",
    sku: "S8-PROFILEPACK-BB",
    price: 99,
    finish: "Brushed Brass",
    dimensions: "For 2000 mm S8 panels",
    features: ["Support arm", "Wall channel", "Converts compatible chrome panel"],
    image: null,
    source: "https://www.scudo.co.uk/products/i8-brushed-brass-wetroom-profile-pack/",
    tags: ["wetroom", "profile", "brushed brass", "support arm", "wall channel"]
  },
  {
    id: "core-wall-tap-chrome",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Core Wall-Mounted Basin Tap",
    sku: "NU-013-V2",
    price: 210,
    finish: "Chrome",
    dimensions: "100 W × 84 H × 182 D mm",
    features: ["Wall mounted", "WRAS approved", "Two handle styles supplied"],
    image: "https://www.scudo.co.uk/app/uploads/2022/04/NU-013_CUTOUT_001-1500x1500.jpg",
    source: "https://www.scudo.co.uk/products/core-wall-mounted-basin-tap-chrome/",
    tags: ["tap", "basin tap", "wall mounted", "chrome", "core", "mixer"]
  },
  {
    id: "core-wall-tap-brass",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Core Wall-Mounted Basin Tap",
    sku: "NU-015-V2",
    price: 263,
    finish: "Brushed Brass",
    dimensions: "Wall-mounted basin mixer",
    features: ["Wall mounted", "WRAS approved", "Two handle styles supplied"],
    image: null,
    source: "https://www.scudo.co.uk/products/core-wall-mounted-basin-tap-brushed-brass/",
    tags: ["tap", "basin tap", "wall mounted", "brushed brass", "core", "mixer"]
  },
  {
    id: "core-wall-tap-black",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Core Wall-Mounted Basin Tap",
    sku: "NU-014-V2",
    price: 263,
    finish: "Matte Black",
    dimensions: "Wall-mounted basin mixer",
    features: ["Wall mounted", "Lever handle", "Two handle styles supplied"],
    image: null,
    source: "https://www.scudo.co.uk/products/core-wall-mounted-basin-tap-black/",
    tags: ["tap", "basin tap", "wall mounted", "black", "core", "mixer"]
  },
  {
    id: "montana-freestanding-mixer",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Montana Freestanding Bath Shower Mixer",
    sku: "MON-040",
    price: 1024,
    finish: "Gunmetal",
    dimensions: "300 W × 860 H × 182 D mm",
    features: ["Freestanding", "Hand shower included", "Soft contemporary shape"],
    image: null,
    source: "https://www.scudo.co.uk/products/montana-bath-shower-mixer-gunmetal/",
    tags: ["bath tap", "freestanding tap", "gunmetal", "montana", "mixer"]
  },
  {
    id: "brass-basin-waste",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Universal Basin Waste",
    sku: "WASTE106BR",
    price: 49,
    finish: "Brushed Brass",
    dimensions: "68 W × 120 H mm",
    features: ["Slotted or unslotted", "Clicker or rigid", "Universal basin use"],
    image: null,
    source: "https://www.scudo.co.uk/products/universal-basin-waste-brushed-brass/",
    tags: ["waste", "basin waste", "brushed brass", "clicker", "slotted"]
  },
  {
    id: "brass-bath-waste",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "Bath Pop-Up Waste with Overflow",
    sku: "BRASSBW001",
    price: 67,
    finish: "Brushed Brass",
    dimensions: "900 mm overflow hose",
    features: ["Bath waste", "Clicker function", "Overflow included"],
    image: null,
    source: "https://www.scudo.co.uk/products/brushed-brass-bath-waste/",
    tags: ["waste", "bath waste", "brushed brass", "overflow", "clicker"]
  },
  {
    id: "bronze-shower-waste",
    category: "Taps & wastes",
    roomGroup: "tap",
    name: "90 mm Fast Flow Shower Waste",
    sku: "S0063",
    price: 68,
    finish: "Brushed Bronze",
    dimensions: "90 mm outlet",
    features: ["Fast flow", "Top fix", "For compatible shower trays"],
    image: null,
    source: "https://www.scudo.co.uk/products/brushed-bronze-90mm-fast-flow-waste/",
    tags: ["waste", "shower waste", "brushed bronze", "90mm", "fast flow"]
  },
  {
    id: "macie-brass-mirror",
    category: "Mirrors & cabinets",
    roomGroup: "mirror",
    name: "Macie Round LED Mirror 600",
    sku: "MACIE-600RND-BB",
    price: 368,
    finish: "Brushed Brass / Mirror",
    dimensions: "600 W × 600 H × 45 D mm",
    features: ["LED lighting", "Demister pad", "Warm-to-cool light change"],
    image: null,
    source: "https://www.scudo.co.uk/products/macie-brushed-brass-led-mirror-600mm/",
    tags: ["mirror", "led mirror", "round", "brushed brass", "macie", "600"]
  },
  {
    id: "macie-black-mirror",
    category: "Mirrors & cabinets",
    roomGroup: "mirror",
    name: "Macie Round LED Mirror 600",
    sku: "MACIE-600RND-BLACK",
    price: 346,
    finish: "Matte Black / Mirror",
    dimensions: "600 mm round",
    features: ["LED lighting", "Demister pad", "Warm-to-cool light change"],
    image: null,
    source: "https://www.scudo.co.uk/products/macie-black-led-mirror-600mm/",
    tags: ["mirror", "led mirror", "round", "black", "macie", "600"]
  },
  {
    id: "alfie-black-mirror",
    category: "Mirrors & cabinets",
    roomGroup: "mirror",
    name: "Alfie Soft-Edge LED Mirror",
    sku: "MIRROR007",
    price: 336,
    finish: "Matte Black / Mirror",
    dimensions: "500 W × 700 H × 32 D mm",
    features: ["Portrait or landscape", "Demister pad", "Dimmable warm/cool lighting"],
    image: null,
    source: "https://www.scudo.co.uk/products/alfie-led-mirror-black-500-700/",
    tags: ["mirror", "led mirror", "black", "alfie", "500", "700"]
  },
  {
    id: "mosca-led-mirror",
    category: "Mirrors & cabinets",
    roomGroup: "mirror",
    name: "Mosca LED Mirror with Shaver Socket",
    sku: "MIRROR001",
    price: 567,
    finish: "Mirror",
    dimensions: "500 W × 700 H × 55 D mm",
    features: ["Shaver socket", "Demister pad", "Infrared sensor"],
    image: null,
    source: "https://www.scudo.co.uk/products/mosca-led-mirror-with-demister-pad-and-shaver-socket-500x700mm/",
    tags: ["mirror", "led mirror", "shaver socket", "mosca", "demister"]
  },
  {
    id: "charj-led-mirror",
    category: "Mirrors & cabinets",
    roomGroup: "mirror",
    name: "CHARJ LED Mirror 500 × 700",
    sku: "MIRROR021",
    price: 431,
    finish: "Mirror",
    dimensions: "500 W × 720 H × 115 D mm",
    features: ["Wireless charging pad", "Toothbrush charging point", "Integrated shelf"],
    image: null,
    source: "https://www.scudo.co.uk/products/charj-led-mirror-500x700/",
    tags: ["mirror", "led mirror", "wireless charging", "charj", "shelf"]
  },
  {
    id: "bravo-radiator",
    category: "Heating",
    roomGroup: "heating",
    name: "Bravo Designer Radiator 1800 × 544",
    sku: "BRAV1800-54S-W",
    price: 420,
    finish: "White",
    dimensions: "544 W × 1800 H × 52 D mm",
    features: ["Vertical radiator", "2949 BTU at 50°C", "Wall mounted"],
    image: null,
    source: "https://www.scudo.co.uk/products/bravo-designer-radiator-1800-x-544/",
    tags: ["radiator", "heating", "bravo", "white", "vertical", "1800"]
  },
  {
    id: "bravo-double-radiator",
    category: "Heating",
    roomGroup: "heating",
    name: "Bravo Double Designer Radiator 1800 × 408",
    sku: "BRAV1800-41D-W",
    price: 568,
    finish: "White",
    dimensions: "408 W × 1800 H × 69 D mm",
    features: ["Double panel", "4485 BTU at 50°C", "Vertical radiator"],
    image: null,
    source: "https://www.scudo.co.uk/products/bravo-double-designer-radiator-1800-x-408/",
    tags: ["radiator", "heating", "bravo", "white", "vertical", "double"]
  },
  {
    id: "heating-element-150",
    category: "Heating",
    roomGroup: "heating",
    name: "150 W Heating Element",
    sku: "HB150WSC",
    price: 66,
    finish: "Chrome",
    dimensions: "25 W × 370 H mm",
    features: ["150 W", "IPX6", "For compatible radiators"],
    image: null,
    source: "https://www.scudo.co.uk/products/150w-heating-element-2/",
    tags: ["heating element", "radiator", "chrome", "150w", "electric"]
  },
  {
    id: "brass-niche-600",
    category: "Accessories",
    roomGroup: "accessory",
    name: "Inset Shower Niche 600 × 300",
    sku: "SN-6X3-BBRASS",
    price: 175,
    finish: "Brushed Brass",
    dimensions: "600 W × 300 H × 83 D mm",
    features: ["Wall insert", "Moisture resistant", "Ready-finished storage"],
    image: null,
    source: "https://www.scudo.co.uk/products/inset-shower-niche-600x300mm-brushed-brass/",
    tags: ["niche", "shower niche", "brushed brass", "600", "storage"]
  },
  {
    id: "brass-niche-300",
    category: "Accessories",
    roomGroup: "accessory",
    name: "Inset Shower Niche 300 × 300",
    sku: "SN-3X3-BBRASS",
    price: 150,
    finish: "Brushed Brass",
    dimensions: "300 W × 300 H × 80 D mm",
    features: ["Wall insert", "Stainless steel", "Compact storage"],
    image: null,
    source: "https://www.scudo.co.uk/products/inset-shower-niche-300x300mm-brushed-brass/",
    tags: ["niche", "shower niche", "brushed brass", "300", "storage"]
  },
  {
    id: "roma-double-towel-rail",
    category: "Accessories",
    roomGroup: "accessory",
    name: "Roma Double Towel Rail",
    sku: "BRASSACC-005",
    price: 173,
    finish: "Brushed Brass",
    dimensions: "598 W × 119 H mm",
    features: ["Double rail", "Wall mounted", "Matching Roma accessories available"],
    image: null,
    source: "https://www.scudo.co.uk/products/roma-double-towel-rail-brushed-brass/",
    tags: ["towel rail", "accessory", "brushed brass", "roma", "double"]
  }
];

window.DLS_CATEGORIES = [
  "All products",
  "Toilets & sanitaryware",
  "Furniture & basins",
  "Baths",
  "Showers",
  "Screens & wetrooms",
  "Taps & wastes",
  "Mirrors & cabinets",
  "Heating",
  "Accessories"
];
