'use strict';
(() => {
 const $=id=>document.getElementById(id),data=JSON.parse($('catalogue-data').textContent),products=new Map(data.flatMap(d=>d.products.map(p=>[p.ref,{...p,look:d}]))),base=new URL('./',document.baseURI).href;
 const storageKey='dls-bathroom-shortlist-v1',saveKey='dls-bathroom-saved-v1',query=new URLSearchParams(location.search);
 let chosen=new Set(),saved=new Set(),view='all',recommended=null,toastTimer,mountedPanel=null,mountedHome=null,currentProduct=null,activeDialog=null,panelReturn=null;
 const valid=refs=>Array.isArray(refs)&&refs.length<=products.size&&refs.every(r=>typeof r==='string'&&products.has(r));
 const validLooks=ns=>Array.isArray(ns)&&ns.length<=20&&ns.every(n=>Number.isInteger(n)&&data.some(d=>d.n===n));
 function fromStorage(key){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[];}catch{return [];}}
 function decode(s){if(!s||s.length>10000)return [];const refs=s.split(',');return valid(refs)?refs:[];}
 chosen=new Set(query.has('items')?decode(query.get('items')):fromStorage(storageKey).filter(r=>products.has(r)));
 const savedQuery=(query.get('saved')||'').split(',').filter(Boolean).map(Number);saved=new Set(query.has('saved')?(validLooks(savedQuery)?savedQuery:[]):fromStorage(saveKey).filter(n=>data.some(d=>d.n===n)));if(query.has('saved'))view='saved';
 function ids(){return [...chosen].sort((a,b)=>{const A=a.split('.').map(Number),B=b.split('.').map(Number);return A[0]-B[0]||A[1]-B[1];});}
 const lookURL=n=>new URL('look/'+String(n).padStart(2,'0')+'/',base).href;
 function shareURL(){const u=new URL(base);u.searchParams.set('items',ids().join(','));return u.href;}
 function savedURL(){const u=new URL(base);u.searchParams.set('saved',[...saved].sort((a,b)=>a-b).join(','));return u.href;}
 function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
 async function copy(text){try{await navigator.clipboard.writeText(text);toast('Link copied — ready for WhatsApp');}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'Link copied — ready for WhatsApp':'Copy is unavailable. Use Download product list.');}}
 async function share(url,title,text){if(navigator.share){try{await navigator.share({url,title,text});return;}catch(e){if(e.name==='AbortError')return;}}await copy(url);}
 function el(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
 function restorePanel(){if(mountedPanel&&mountedHome){mountedHome.append(mountedPanel);mountedHome.open=false;}mountedPanel=null;mountedHome=null;}
 function hideDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());restorePanel();activeDialog=null;document.body.classList.remove('sheet-open');}
 function openDialog(id){const already=!!activeDialog;hideDialogs();if(!already){panelReturn=location.href;history.pushState({dlsPanel:true},'',location.pathname+location.search+'#panel-'+id);}else history.replaceState({dlsPanel:true},'',location.pathname+location.search+'#panel-'+id);activeDialog=$(id);activeDialog.showModal();document.body.classList.add('sheet-open');}
 function closeDialog(){if(history.state?.dlsPanel){history.back();}else{hideDialogs();if(panelReturn)history.replaceState(null,'',panelReturn);}}
 window.addEventListener('popstate',()=>{hideDialogs();});
 document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});});
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',closeDialog));
 function render(){try{localStorage.setItem(storageKey,JSON.stringify(ids()));}catch{}document.querySelectorAll('[data-ref]').forEach(x=>x.checked=chosen.has(x.dataset.ref));$('count').textContent=chosen.size;$('nav-count').textContent=chosen.size;
  const list=$('selection-items');list.replaceChildren();if(!chosen.size)list.append(el('p','Your shortlist is empty. Choose a whole bathroom or individual products.'));
  let last=null;for(const id of ids()){const p=products.get(id);if(last!==p.look.n){list.append(el('h3',p.look.id+' · '+p.look.name,'selection-group'));last=p.look.n;}const row=el('div',null,'selection-row'),info=el('div'),a=el('a',p.number+'. '+p.name);a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';info.append(a,el('small',[p.code,p.finish,p.size,'Qty: '+p.quantity].filter(Boolean).join(' · ')));const remove=el('button','Remove');remove.type='button';remove.setAttribute('aria-label','Remove '+p.name);remove.addEventListener('click',()=>{chosen.delete(id);render();});row.append(info,remove);list.append(row);}
  document.querySelector('.share-actions').hidden=!chosen.size;const looks=[...new Set(ids().map(id=>products.get(id).look.id))];const message='Hi DLS, please check availability and quote for my bathroom shortlist ('+looks.join(', ')+').\n\n'+shareURL()+'\n\nThis link contains my selected products and supplier codes. Please confirm stock, sizes and fitting details with me.';$('whatsapp').href='https://wa.me/447539037841?text='+encodeURIComponent(message);
 }
 function stage(refs,mode='add'){if(!valid(refs)||!['add','replace','remove'].includes(mode))throw new Error('Use valid product references and add, replace or remove.');if(mode==='replace')chosen=new Set(refs);else refs.forEach(r=>mode==='remove'?chosen.delete(r):chosen.add(r));render();return {count:chosen.size,refs:ids(),shareUrl:shareURL()};}
 function addLook(n){const d=data.find(d=>d.n===n);if(!d)return;stage(d.products.filter(p=>!p.optional).map(p=>p.ref));toast(d.id+' added to your quote shortlist');}
 function renderSaved(){try{localStorage.setItem(saveKey,JSON.stringify([...saved]));}catch{}$('saved-count').textContent=saved.size;document.querySelectorAll('[data-save-look]').forEach(b=>{const yes=saved.has(+b.dataset.saveLook);b.setAttribute('aria-pressed',String(yes));b.querySelector('[aria-hidden]').textContent=yes?'♥':'♡';b.querySelector('.save-label').textContent=yes?'Saved':'Save';b.setAttribute('aria-label',(yes?'Unsave ':'Save ')+data.find(d=>d.n===+b.dataset.saveLook).name);});}
 const grid=document.querySelector('.grid');function visibleCards(){return [...grid.querySelectorAll('.look:not([hidden])')];}
 function swipePosition(){const cards=visibleCards();let closest=0,distance=Infinity;cards.forEach((card,i)=>{const gap=Math.abs(card.getBoundingClientRect().left-grid.getBoundingClientRect().left);if(gap<distance){distance=gap;closest=i;}});$('swipe-position').textContent=cards.length?`${closest+1} of ${cards.length}`:'0 looks';$('previous-look').disabled=closest===0;$('next-look').disabled=closest>=cards.length-1;return closest;}
 function scrollCard(card){if(!card)return;if(matchMedia('(max-width:700px)').matches)grid.scrollTo({left:card.offsetLeft-grid.offsetLeft,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});else card.scrollIntoView({behavior:'smooth',block:'start'});}
 function filter(){let total=0;grid.querySelectorAll('.look').forEach(card=>{const n=+card.id.replace('look-',''),mode=view==='saved'?saved.has(n):recommended?recommended.includes(n):true;const show=mode&&['room','metal','light'].every(k=>!$(k).value||card.dataset[k]===$(k).value);card.hidden=!show;if(show)total++;});$('result-count').textContent=total+' '+(total===1?'look':'looks');$('empty-results').hidden=total!==0;$('empty-results').textContent=view==='saved'?'No saved looks match. Tap Save on a bathroom you like, or clear your filters.':'No looks match those filters. Try another finish or browse all 20 looks.';$('view-title').textContent=view==='saved'?'Your saved looks':recommended?'Ideas to start with':'All bathroom ideas';$('view-note').textContent=view==='saved'?'Keep your favourites together, then ask us about them.':recommended?'Suggested from your answers. Room fit is confirmed with DLS.':'Browse, save, or choose a whole look.';$('saved-actions').hidden=view!=='saved'||!saved.size;document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});grid.scrollLeft=0;swipePosition();}
 function setView(next){view=next;recommended=null;['room','metal','light'].forEach(id=>$(id).value='');filter();$('collection').scrollIntoView({behavior:'smooth',block:'start'});}
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('browse-all').addEventListener('click',()=>setView('all'));
 document.querySelectorAll('[data-save-look]').forEach(b=>b.addEventListener('click',()=>{const n=+b.dataset.saveLook;saved.has(n)?saved.delete(n):saved.add(n);renderSaved();if(view==='saved')filter();}));
 document.querySelectorAll('[data-ref]').forEach(input=>input.addEventListener('change',()=>stage([input.dataset.ref],input.checked?'add':'remove')));
 document.querySelectorAll('[data-add-look]').forEach(b=>b.addEventListener('click',()=>addLook(+b.dataset.addLook)));
 document.querySelectorAll('[data-share-look]').forEach(b=>b.addEventListener('click',()=>{const d=data.find(d=>d.n===+b.dataset.shareLook);share(lookURL(d.n),d.name+' | DLS Bathroom Ideas','What do you think of '+d.name+'? View this bathroom idea and its products.');}));
 $('share-collection').addEventListener('click',()=>share(base,'DLS Bathroom Ideas','Need some bathroom inspiration? Browse these 20 ideas and save your favourites.'));
 $('share-saved').addEventListener('click',()=>share(savedURL(),'My saved DLS bathroom ideas','These are the bathroom looks I like.'));
 $('send-saved').addEventListener('click',()=>{const names=data.filter(d=>saved.has(d.n)).map(d=>d.id+' — '+d.name).join('\n');location.href='https://wa.me/447539037841?text='+encodeURIComponent('Hi DLS, these are the bathroom styles I like. Please help me choose what works for my room.\n\n'+names+'\n\n'+savedURL());});
 document.querySelectorAll('.schedule summary').forEach(summary=>summary.addEventListener('click',e=>{e.preventDefault();const schedule=summary.parentElement,n=+schedule.id.replace('products-',''),d=data.find(d=>d.n===n);openDialog('product-dialog');mountedHome=schedule;mountedPanel=schedule.querySelector('.product-panel');$('product-content').append(mountedPanel);currentProduct=n;$('product-title').textContent=d.name;$('product-look-id').textContent=d.id+' / products';$('product-dialog').scrollTop=0;}));
 $('product-add-look').addEventListener('click',()=>addLook(currentProduct));$('product-review').addEventListener('click',()=>openDialog('shortlist'));
 document.querySelectorAll('.image-link').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const d=data.find(d=>d.n===+a.closest('.look').id.replace('look-',''));$('large-image').src=d.image;$('large-image').alt='AI concept: '+d.description;$('image-title').textContent=d.id+' · '+d.name;openDialog('image-dialog');}));
 $('open-shortlist').addEventListener('click',()=>openDialog('shortlist'));$('nav-shortlist').addEventListener('click',()=>openDialog('shortlist'));$('shortlist-browse').addEventListener('click',closeDialog);
 $('copy-selection').addEventListener('click',()=>copy(shareURL()));$('clear-selection').addEventListener('click',()=>{stage([],'replace');toast('Shortlist cleared');});
 $('download-selection').addEventListener('click',()=>{let text='DLS Bathroom Ideas — availability and quote request\nSource check: 5 October 2026\n'+shareURL()+'\n\n';for(const id of ids()){const p=products.get(id);text+=p.look.id+' / '+p.number+'. '+p.category+': '+p.name+'\n'+[p.brand,p.code,p.finish,p.size,'Qty: '+p.quantity].filter(Boolean).join(' | ')+'\n'+p.url+'\n'+p.note+'\n\n';}text+='Stock, samples, measurements and installation to be confirmed by DLS before ordering.\n';const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=el('a');a.href=url;a.download='DLS-bathroom-shortlist.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 ['room','metal','light'].forEach(id=>$(id).addEventListener('change',filter));$('reset').addEventListener('click',()=>{['room','metal','light'].forEach(id=>$(id).value='');filter();});
 grid.addEventListener('scroll',swipePosition,{passive:true});window.addEventListener('resize',swipePosition);$('previous-look').addEventListener('click',()=>scrollCard(visibleCards()[swipePosition()-1]));$('next-look').addEventListener('click',()=>scrollCard(visibleCards()[swipePosition()+1]));grid.addEventListener('keydown',e=>{if(e.target===grid&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();scrollCard(visibleCards()[swipePosition()+(e.key==='ArrowRight'?1:-1)]);}});
 const questions=[{title:'What room are you planning?',explain:'A starting point is all we need.',choices:[['bath','A bathroom with a bath'],['shower','A shower room or en suite'],['cloak','A cloakroom / downstairs toilet'],['any','Still deciding']]},{title:'What feeling do you like?',explain:'Choose what feels closest. Nothing is fixed.',choices:[['warm','Warm and calm'],['colour','Colour and character'],['clean','Light and simple'],['any','Show me a mixture']]},{title:'Which metal finish appeals?',explain:'We can change the details when we plan your room.',choices:[['Brushed Brass','Brass'],['Brushed Bronze','Bronze'],['Chrome','Chrome'],['Matte Black','Black'],['Gunmetal','Gunmetal'],['any','I’m not sure yet']]}];let step=0,answers=[];
 function showQuestion(){const q=questions[step];$('help-step').textContent='Question '+(step+1)+' of 3';$('help-title').textContent=q.title;$('help-explanation').textContent=q.explain;$('help-back').hidden=step===0;const options=$('help-options');options.replaceChildren();q.choices.forEach(([value,label])=>{const b=el('button',label);b.type='button';b.dataset.answer=value;b.addEventListener('click',()=>{answers[step]=value;if(step<2){step++;showQuestion();}else finishHelp();});options.append(b);});}
 function finishHelp(){const [room,mood,finish]=answers;let pool=data.filter(d=>room==='any'||(room==='cloak'?d.room==='Cloakroom':room==='shower'?['Shower room','Compact en suite'].includes(d.room):['Bathroom','Double basin'].includes(d.room)));const moods={warm:[1,2,3,8,9,10,11,12,13,17,19],colour:[2,3,4,6,9,13,14,18,19,20],clean:[5,7,8,11,15,16,20]};const score=d=>(d.metal===finish?3:0)+(moods[mood]?.includes(d.n)?2:0);pool.sort((a,b)=>score(b)-score(a)||a.n-b.n);recommended=pool.slice(0,3).map(d=>d.n);view='all';['room','metal','light'].forEach(id=>$(id).value='');filter();closeDialog();$('collection').scrollIntoView({behavior:'smooth',block:'start'});toast('Here '+(recommended.length===1?'is a starting idea':'are '+recommended.length+' starting ideas')+' for your room');}
 document.querySelectorAll('[data-help]').forEach(b=>b.addEventListener('click',()=>{step=0;answers=[];showQuestion();openDialog('help-dialog');}));$('help-back').addEventListener('click',()=>{if(step>0){step--;showQuestion();}});
 render();renderSaved();filter();const requestedLook=Number(query.get('look')||location.hash.replace('#look-',''));if(data.some(d=>d.n===requestedLook)){requestAnimationFrame(()=>{$('collection').scrollIntoView({block:'start'});scrollCard($('look-'+requestedLook));});}if(query.has('help')){showQuestion();openDialog('help-dialog');}else if(query.has('items')&&chosen.size)openDialog('shortlist');
 const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_bathroom_shortlist',description:'Read selected bathroom product references and the share link.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({count:chosen.size,refs:ids(),shareUrl:shareURL()})});
 register({name:'stage_bathroom_shortlist',description:'Add, replace or remove product references in the visible quote shortlist. Does not send a message or place an order.',inputSchema:{type:'object',properties:{refs:{type:'array',items:{type:'string'}},mode:{type:'string',enum:['add','replace','remove']}},required:['refs','mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['refs','mode'].includes(k)))throw new Error('Invalid input');return stage(input.refs,input.mode);}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
