"""Build the public inspiration page from the reviewed, public-only data file."""
import json,html
from pathlib import Path
from urllib.parse import quote
ROOT=Path(__file__).resolve().parent.parent
ds=json.loads((ROOT/'inspiration-data.json').read_text())
e=html.escape
def wa(d):return 'https://wa.me/447539037841?text='+quote(f"Hello DLS Bathrooms, I like {d['id']} — {d['name']} from your inspiration collection. Please help me adapt this look to my room and confirm products, availability and a supply-and-fit quotation.\nMy postcode: \nRoom size: \nChanges I would like: ")
def card(d):
 n=d['n'];tid=f'{n:02d}'
 tile=''.join(f'<a class="tile-link" href="{e(t["url"])}" target="_blank" rel="noopener noreferrer">{e(t["role"])}: {e(t["name"])} ↗</a>' for t in d['tiles'])
 sw=''.join(f'<span class="swatch" style="--swatch:{c}" title="Approximate palette {c}"></span>' for c in d['palette'])
 return f'''<article class="look" id="look-{tid}" data-n="{n}" data-room="{e(d['room'])}" data-style="{e(d['style'])}" data-lighting="{e(d['light'])}">
<a class="look-image" href="{d['image']}" data-open="{n}" aria-label="Enlarge {e(d['name'])}"><img src="{d['thumbnail']}" srcset="{d['thumbnail']} 720w, {d['image']} 1536w" sizes="(max-width:650px) 92vw, 45vw" alt="AI bathroom concept: {e(d['name'])}. {e(d['description'])}" width="1536" height="1024" loading="lazy" decoding="async"/><span class="concept-tag">AI-GENERATED DESIGN CONCEPT</span>{'<span class="new-tag">New look</span>' if d['new'] else ''}</a>
<div class="look-heading"><div><span class="look-id">{d['id']} / {e(d['room']).upper()}</span><h3>{e(d['name'])}</h3></div><button type="button" class="save js-only" data-save="{n}" aria-pressed="false" aria-label="Save {e(d['name'])} to favourites">♡</button></div>
<p class="look-desc">{e(d['description'])}</p><div class="tags"><span>{e(d['metal'])}</span><span>{d['kelvin']}K {d['light'].lower()}</span><span>{e(d['style'])}</span></div><div class="swatches" aria-label="Approximate digital colour palette">{sw}</div>
<details><summary>Materials, tiles &amp; lighting</summary><div class="spec"><dl><dt>Furniture direction</dt><dd>{e(d['furniture'])}</dd><dt>Suggested tile sources</dt><dd>{tile}<span class="fine">Tiles supplied separately by Mandarin Stone. Confirm samples, sizes, quantities and suitability with your quotation.</span></dd><dt>Lighting direction</dt><dd>{d['kelvin']}K {d['light'].lower()} for the niche and room lighting. Mirror settings vary. The niche lighting is a separate installation detail.</dd></dl><p class="fine">This AI image illustrates a style. Final fittings, dimensions, tile patterns, colours, stock and price are confirmed for your room before ordering. Digital palette values: {', '.join(d['palette'])}; these are not manufacturer finish codes.</p></div></details>
<div class="look-actions"><a href="{e(wa(d))}" target="_blank" rel="noopener noreferrer">Ask us about this look ↗</a><a class="open-link" href="/quote?looks={n}">Add room details →</a></div></article>'''
def options(field,label):return '<option value="">'+label+'</option>'+''.join(f'<option>{e(x)}</option>' for x in dict.fromkeys(d[field] for d in ds))
cards='\n'.join(card(d) for d in ds)
data=json.dumps(ds,ensure_ascii=False).replace('<','\\u003c')
page='''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>20 Bathroom Inspiration Looks | DLS Bathrooms</title><meta name="description" content="Explore 20 DLS bathroom design concepts. Compare tiles, finishes and lighting, save favourites and ask DLS to adapt a look to your room in Stockport or Manchester."><link rel="canonical" href="https://dlsbathrooms.co.uk/inspiration"><meta property="og:title" content="Find your bathroom style | DLS Bathrooms"><meta property="og:description" content="20 AI bathroom concepts, curated by DLS. Choose a look and make it your own."><meta property="og:type" content="website"><meta property="og:url" content="https://dlsbathrooms.co.uk/inspiration"><meta property="og:image" content="https://dlsbathrooms.co.uk/inspiration-images/look-12.webp"><meta property="og:image:alt" content="Floating Oak — an AI bathroom design concept"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/inspiration.css"><link rel="preload" href="/inspiration-images/look-12.webp" as="image"><script defer src="/inspiration.js"></script></head><body>
<a class="skip" href="#main">Skip to collection</a><header class="catalogue-header"><a class="catalogue-brand" href="/" aria-label="DLS Bathrooms home"><b>DLS</b><span>Bathrooms<small>DESIGNED AROUND YOU</small></span></a><nav aria-label="Catalogue navigation"><a href="#collection">The collection</a><a href="/#work">Our completed work</a><a href="/inspiration-magazine.pdf" target="_blank">Download magazine</a></nav><a class="btn" href="/quote">Plan your bathroom ↗</a></header>
<main id="main"><div class="wrap"><div class="masthead"><div><p class="kicker">The DLS inspiration collection</p><h1>A bathroom that<br>feels <em>like you.</em></h1></div><p class="edition"><strong>20 looks. Endless starting points.</strong>Materials, colour and light, brought together for your next bathroom.</p></div>
<section class="feature" aria-labelledby="feature-title"><figure class="feature-photo"><a href="/inspiration-images/look-12.webp" data-open="12" aria-label="Explore Floating Oak"><img src="/inspiration-images/look-12.webp" alt="Floating Oak: AI concept with open oak shelf, bronze basin and fluted bath" width="1536" height="1024" fetchpriority="high"></a><figcaption class="concept-tag">DLS-12 · FLOATING OAK · AI CONCEPT</figcaption></figure><div class="feature-copy"><p class="kicker">Choose a look. Make it yours.</p><h2>Start with the feeling.<br>We’ll work on the details.</h2><p>Warm and natural, bold and colourful, or crisp and minimal. Explore our bathroom ideas, save the ones you love, and let DLS help shape them around your space.</p><div class="actions"><a class="btn" href="#collection">Explore all 20 looks ↓</a><a class="btn light" href="/inspiration-magazine.pdf" target="_blank">Read the magazine ↗</a></div><p class="fine">These are AI-generated design concepts, not photographs of completed DLS installations. See <a href="/#work">our real work</a> for the finish we deliver.</p></div></section>
<div class="intro-note"><div><b>01 / Find your style</b><p>Compare furniture, tile, metal finishes and warm or cool lighting. Mix favourite details from different looks.</p></div><div><b>02 / Share your room</b><p>Send your shortlist with photographs, rough measurements and your postcode. We’ll discuss what fits.</p></div><div><b>03 / Confirm the details</b><p>Your quotation confirms the actual products, samples, layout, availability and installation scope before ordering.</p></div></div>
<section class="collection" id="collection" aria-labelledby="collection-title"><div class="section-heading"><div><p class="kicker">Curated by DLS Bathrooms</p><h2 id="collection-title">Find your favourite.</h2></div><p>Tap a photograph to take a closer look.</p></div>
<div class="filters js-only" aria-label="Filter bathroom concepts"><label for="room">Room type<select id="room">ROOM_OPTIONS</select></label><label for="style">Style<select id="style">STYLE_OPTIONS</select></label><label for="lighting">Lighting<select id="lighting">LIGHT_OPTIONS</select></label><div class="filter-buttons"><button class="btn light" id="saved-filter" type="button" aria-pressed="false">Favourites (0)</button><button class="btn light" type="button" data-reset>Reset</button></div></div><noscript><p class="no-js-note">All 20 looks are shown below. Open “Materials, tiles &amp; lighting” for details, or use an enquiry link to discuss a look.</p></noscript><div class="result-row"><span id="result-count" aria-live="polite">20 of 20 looks</span><span>All images are AI concepts · Colours are indicative</span></div><div id="empty" class="empty" hidden><h3>No looks in this selection yet.</h3><p>Try a different filter, or save a favourite with the heart button.</p><button class="btn light" data-reset type="button">Show all looks</button></div><div class="gallery">CARDS</div></section>
<section class="next-step" aria-labelledby="next-title"><div class="next-copy"><p class="kicker">From an idea to your home</p><h2 id="next-title">Love the tiles in one?<br>The furniture in another?</h2><p>That’s a useful place to start. Tell us which details you like and what you would change. DLS can work through a practical layout and a confirmed product selection for your own room.</p><div class="actions"><a class="btn" href="/quote">Tell us about your room ↗</a><a class="btn light" href="/video-estimate">Send photos for an estimate</a></div></div><div class="next-image"><img src="/inspiration-images/look-13.webp" alt="Earth and Brass AI bathroom concept with earth-red furniture and white fluted bath" width="1536" height="1024" loading="lazy"><span class="concept-tag">DLS-13 · EARTH &amp; BRASS · AI CONCEPT</span></div></section>
<section class="faq" aria-labelledby="faq-title"><h2 id="faq-title">A few useful details.</h2><details><summary>Can you recreate one of these bathrooms?</summary><p>We can use a look as the starting point for your design and quotation. The final layout and products must suit your room, services, budget and available stock. AI images can vary from the exact shape, colour and scale of real products, so we confirm those details with you before ordering.</p></details><details><summary>Where do the tiles come from?</summary><p>Each look includes named Mandarin Stone tile suggestions under “Materials, tiles &amp; lighting”. Those links let you see the actual range and request samples. Tile patterns and colours in the images are illustrative; physical samples and the supplier’s specifications take precedence.</p></details><details><summary>Are the illuminated niches included as a product?</summary><p>The niche and its lighting are planned as separate elements. We confirm a suitable niche, waterproofing and electrical lighting detail for the room. The glow shown in these images does not mean the niche is supplied with an integrated light.</p></details><details><summary>Where can I see bathrooms DLS has actually completed?</summary><p>Visit <a href="/#work">our completed-work gallery</a> for photographs of real DLS installations. This inspiration collection is labelled separately because every image here is AI-generated.</p></details><details><summary>How are my favourites saved?</summary><p>Favourites are stored in this browser. Use “Copy shortlist link” to share them or return to the same selection on another device. Your shortlist is only sent to DLS when you choose to send your WhatsApp message.</p></details></section></div></main>
<footer class="catalogue-footer"><div class="wrap"><div class="footer-row"><div><strong>DLS Bathrooms Ltd</strong>Bathroom design, supply and installation<br>Stockport · Manchester · Surrounding areas</div><div><a href="tel:+447539037841">07539 037841</a><a href="mailto:info@dlsbathrooms.co.uk">Email DLS</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/">Back to our website</a></div></div><p class="fine">© 2026 DLS Bathrooms Ltd. AI-generated concept collection. Images are visual starting points; final products and installation are agreed individually. Tile suppliers are credited on each look.</p></div></footer>
<aside class="shortlist" id="shortlist" aria-label="Your favourite bathrooms" hidden><div class="shortlist-copy"><strong id="saved-count"></strong><span id="saved-codes"></span></div><a class="btn share-selection" id="enquire-saved" href="https://wa.me/447539037841" target="_blank" rel="noopener noreferrer">Discuss on WhatsApp ↗</a><a class="btn light" id="quote-saved" href="/quote">Add room details</a><button class="btn light" id="copy-shortlist" type="button">Copy shortlist link</button><div id="share-fallback" hidden><label for="share-url">Shortlist link</label><input id="share-url" readonly></div></aside>
<dialog id="look-dialog" aria-labelledby="dialog-title"><div class="dialog-toolbar"><span id="dialog-code"></span><button id="close-dialog" aria-label="Close image" type="button">×</button></div><img id="dialog-image" alt="" width="1536" height="1024"><div class="dialog-footer"><div><h2 id="dialog-title"></h2><p>AI concept · Product shapes, tile patterns and colours are illustrative.</p></div><div class="actions"><button class="save" id="dialog-save" type="button" aria-label="Save this look" aria-pressed="false">♡</button><a id="dialog-details" class="btn light" href="#collection">See materials</a><a id="dialog-whatsapp" class="btn" href="https://wa.me/447539037841" target="_blank" rel="noopener noreferrer">Discuss this look ↗</a></div></div></dialog><div class="toast" id="toast" role="status" hidden></div><script type="application/json" id="look-data">DATA</script></body></html>'''
page=page.replace('ROOM_OPTIONS',options('room','All rooms')).replace('STYLE_OPTIONS',options('style','All styles')).replace('LIGHT_OPTIONS',options('light','All lighting')).replace('CARDS',cards).replace('DATA</script>',data+'</script>')
(ROOT/'inspiration.html').write_text(page)
print('Built inspiration.html with',len(ds),'static, accessible concept cards.')
