const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:4174',looks=JSON.parse(fs.readFileSync(path.join(root,'ideas/catalogue-data.json'))),config=JSON.parse(fs.readFileSync(path.join(root,'ideas/customiser-data.json')));
const types={'.js':'text/javascript','.html':'text/html','.json':'application/json','.css':'text/css','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png'};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(new URL(req.url,base).pathname));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)&&!path.extname(p))p+='.html';if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',types[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res);});
const executablePath=process.env.PICKER_BROWSER;const args=executablePath?['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']:[];
(async()=>{await new Promise(r=>server.listen(4174,'127.0.0.1',r));const b=await chromium.launch({headless:true,executablePath,args});let errors=[];const p=await b.newPage({viewport:{width:1280,height:950}});p.on('pageerror',e=>errors.push(e.message));let checked=0;fs.mkdirSync(path.join(root,'tmp/picker'),{recursive:true});
try{
 for(const room of (process.env.PICKER_LOOKS?looks.filter(r=>process.env.PICKER_LOOKS.split(',').map(Number).includes(r.n)):looks)){await p.goto(base+'/ideas/customise/?look='+room.n);await p.waitForFunction(()=>window.dlsCustomiser);assert.equal(await p.locator('#error').isVisible(),false);assert.equal(await p.evaluate(()=>window.dlsCustomiser.visual?.type),'live-3d');
 const before=await p.locator('#live-room canvas').evaluate(c=>c.toDataURL());const current=await p.evaluate(()=>window.dlsCustomiser.state.wall);const next=current==='8fe7b042'?'9f95cd40':'8fe7b042';await p.selectOption('#wall-select',next);assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.wall),next);assert.notEqual(await p.locator('#live-room canvas').evaluate(c=>c.toDataURL()),before);assert((await p.evaluate(()=>window.dlsCustomiser.products)).some(x=>x.url===config.tiles.find(t=>t.id===next).url));
 await p.locator('#undo-design').click();assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.wall),current);await p.locator('#redo-design').click();assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.wall),next);await p.locator('#reset').click();
 if(room.n>=51){await p.waitForTimeout(120);await p.locator('#live-room canvas').screenshot({path:path.join(root,'tmp/picker/layout-'+room.n+'.png')});}
 checked++;if(checked%10===0)console.log(checked+' rooms verified');}
 await p.goto(base+'/ideas/customise/?look=52');await p.waitForFunction(()=>window.dlsCustomiser);await p.locator('.advanced-options').click();
 for(const tile of config.tiles){await p.selectOption('#wall-select',tile.id);assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.wall),tile.id);}
 const packages=await p.locator('#basin-select option').evaluateAll(es=>es.map(e=>e.value));for(const pkg of packages){await p.selectOption('#basin-select',pkg);assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.basin),pkg);}
 const mirrors=await p.locator('#mirror-select option').evaluateAll(es=>es.map(e=>e.value));for(const mirror of mirrors){await p.selectOption('#mirror-select',mirror);assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.mirror),mirror);if(mirror!=='original')assert((await p.evaluate(()=>window.dlsCustomiser.products)).some(x=>x.category==='Mirror'&&x.code===mirror));}
 for(const finish of config.finishes){await p.locator('[data-finish="'+finish+'"]').click();assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.finish),finish);}
 for(const [id,values] of [['shape-select',['rectangle','L-shaped','loft','offset']],['structure-select',['clean','half','full','ledge']],['coverage-select',['all','feature','half']],['toilet-select',['close','wall']],['worktop-select',['oak','dark-stone','pure-white','marble-light']],['pattern-select',['vertical','stacked']],['grout-select',['white','dark','matched']],['lighting-select',['cool','warm']],['niche-select',['with','without']]])for(const value of values)await p.selectOption('#'+id,value);
 await p.selectOption('#shower-floor-select','wet');const floorOptions=await p.locator('#floor-select option').evaluateAll(es=>es.map(e=>e.value));assert(floorOptions.filter(x=>x!=='original').every(x=>config.tiles.find(t=>t.id===x).wet_room_floors===true));await p.selectOption('#floor-select','1df57186');assert(!(await p.evaluate(()=>window.dlsCustomiser.review)).some(x=>x.includes('no verified wetroom')));
 await p.locator('#room-width').fill('1.35');await p.locator('#room-width').press('Tab');assert.equal(await p.evaluate(()=>window.dlsCustomiser.state.roomWidth),'1.35');
 await p.locator('#save-design').click();assert.equal(await p.locator('#saved-designs a').count(),1);
 const state=await p.evaluate(()=>window.dlsCustomiser.state),shared=await p.evaluate(()=>window.dlsCustomiser.shareUrl);const other=await b.newPage();await other.goto(shared);await other.waitForFunction(()=>window.dlsCustomiser);assert.deepEqual(await other.evaluate(()=>window.dlsCustomiser.state),state);await other.close();
 const downloadPromise=p.waitForEvent('download');await p.locator('#download').click();const dl=await downloadPromise;const content=fs.readFileSync(await dl.path(),'utf8');assert(content.includes(shared));assert(content.includes('1.35'));await p.locator('#quote-form').click();assert((await p.locator('#project-details').inputValue()).includes(shared));
 await p.goto(base+'/ideas/');await p.waitForFunction(()=>document.querySelector('#result-count').textContent==='70 looks');assert.equal(await p.locator('.look').count(),70);await p.locator('.filter-drawer>summary').click();await p.selectOption('#footprint','tiny');const count=await p.locator('.look:not([hidden])').count();assert(count>0&&count<70);await p.locator('#reset').click();assert.equal(await p.locator('.look:not([hidden])').count(),70);
 await p.setViewportSize({width:390,height:844});await p.goto(base+'/ideas/customise/?look=53');await p.waitForFunction(()=>window.dlsCustomiser);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#wall-options').scrollIntoViewIfNeeded();await p.locator('#mobile-room-preview').waitFor({state:'visible'});await p.screenshot({path:path.join(root,'tmp/picker/mobile.png')});await p.locator('#mobile-room-preview').click();await p.locator('#live-room').waitFor({state:'visible'});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({rooms:checked,tiles:config.tiles.length,packages:packages.length,mirrors:mirrors.length,flows:['live visual','undo/redo','finishes','geometry','wetroom suitability','saved version','shared state','download','quote handoff','gallery filters','mobile'],errors},null,2));
}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
