const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const assert=require('assert/strict'),path=require('path'),fs=require('fs');
const base='http://127.0.0.1:4173',out=path.resolve(__dirname,'../../ideas-qa');fs.mkdirSync(out,{recursive:true});
const http=require('http');const root=path.resolve(__dirname,'..');const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.jpg':'image/jpeg','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml','.pdf':'application/pdf','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(['/inspiration','/inspiration.html'].includes(p)){res.writeHead(308,{Location:'/ideas'});return res.end();}let f=path.join(root,p);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');else if(!fs.existsSync(f)&&fs.existsSync(f+'.html'))f+='.html';if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);}).listen(4173,'127.0.0.1',()=>console.log('Testing main website locally'));

(async()=>{const browser=await chromium.launch({executablePath:process.env.PICKER_BROWSER || undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const errors=[];try{
const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await ctx.addInitScript(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async v=>{window.lastShare=v}})});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/ideas');assert.equal(await page.locator('.look').count(),70);assert.equal(await page.locator('.product-link').count(),563);await page.locator('#look-1 img').evaluate(i=>i.decode());await page.screenshot({path:out+'/desktop.png'});
await page.locator('[data-save-look="1"]').click();await page.locator('[data-save-look="12"]').click();assert.equal(await page.locator('#saved-count').textContent(),'2');await page.reload();assert.equal(await page.locator('[data-save-look="12"]').getAttribute('aria-pressed'),'true');await page.locator('[data-view="saved"]').click();assert.equal(await page.locator('.look:visible').count(),2);await page.locator('#share-saved').click();const sharedSaved=await page.evaluate(()=>window.lastShare.url);assert.match(sharedSaved,/\/ideas\/\?saved=1%2C12/);
await page.locator('[data-view="all"]').click();await page.locator('#look-1 summary').click();await page.waitForSelector('#product-dialog[open]');assert.equal(await page.locator('#product-content .product-link').count(),27);await page.locator('#product-content input').first().check();assert.equal(await page.locator('#count').textContent(),'1');await page.goBack();assert.equal(await page.locator('#product-dialog').isVisible(),false);assert.equal(await page.locator('#look-1 .product-panel').count(),1);await page.locator('[data-add-look="1"]').click();await page.locator('#open-shortlist').click();const num=Number(await page.locator('#count').textContent());assert(num>10);const wa=new URL(await page.locator('#whatsapp').getAttribute('href'));assert.equal(wa.pathname,'/447539037841');const share=wa.searchParams.get('text').match(/http[^\s]+/)[0];await page.goto(share);await page.waitForSelector('#shortlist[open]');assert.equal(Number(await page.locator('#count').textContent()),num);await page.locator('#close-shortlist').click();await page.waitForSelector('#shortlist[open]',{state:'detached'});
await page.locator('[data-help]').first().click();await page.locator('[data-answer="cloak"]').click();await page.locator('[data-answer="colour"]').click();await page.locator('[data-answer="Brushed Brass"]').click();await page.waitForSelector('#help-dialog[open]',{state:'detached'});assert.equal(await page.locator('.look:visible').count(),3);assert(await page.locator('#look-18').isVisible());await page.locator('#browse-all').click();await page.locator('.filter-drawer>summary').click();await page.selectOption('#room','Cloakroom');await page.selectOption('#footprint','large');assert.equal(await page.locator('.look:visible').count(),0);assert.equal(await page.locator('#empty-results').isVisible(),true);await page.locator('#reset').click();
await page.goto(base+'/');assert.equal(await page.locator('.gallery-card').count(),80);assert.equal(await page.locator('.inspiration-promo a.button').count(),2);assert.equal(await page.locator('header a[href="/ideas"]').count(),1);await page.screenshot({path:out+'/homepage-desktop.png'});await page.goto(base+'/inspiration');assert(page.url().endsWith('/ideas'));
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await mobile.addInitScript(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async v=>{window.lastShare=v}})});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(base+'/ideas');await m.locator('#look-1 img').evaluate(i=>i.decode());assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:out+'/mobile.png'});await m.locator('#next-look').click();await m.waitForFunction(()=>document.querySelector('#swipe-position').textContent==='2 of 70');await m.locator('[data-share-look="2"]').click();assert.match(await m.evaluate(()=>window.lastShare.url),/\/ideas\/look\/02\/$/);
await m.goto(base+'/ideas?look=12');await m.waitForFunction(()=>document.querySelector('#swipe-position').textContent==='12 of 70');await m.locator('#look-12 summary').click();await m.waitForSelector('#product-dialog[open]');assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:out+'/mobile-products.png'});await m.locator('#product-add-look').click();await m.locator('#product-review').click();await m.waitForSelector('#shortlist[open]');await m.screenshot({path:out+'/mobile-shortlist.png'});await m.goBack();assert.equal(await m.locator('#shortlist').isVisible(),false);
await m.locator('[data-help]').last().click();await m.screenshot({path:out+'/mobile-help.png'});await m.locator('[data-answer="shower"]').click();await m.locator('[data-answer="clean"]').click();await m.locator('[data-answer="Chrome"]').click();await m.waitForSelector('#help-dialog[open]',{state:'detached'});assert.equal(await m.locator('.look:visible').count(),3);assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.setViewportSize({width:320,height:740});assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:out+'/narrow.png'});
const nj=await browser.newContext({javaScriptEnabled:false});const n=await nj.newPage();await n.goto(base+'/ideas');assert.equal(await n.locator('.look').count(),70);await n.locator('#look-1 summary').click();assert(await n.locator('#look-1 .product-link').first().isVisible());await n.goto(base+'/ideas/look/12/');assert.equal(await n.locator('meta[property="og:image"]').getAttribute('content'),'https://dls-bathroom-ideas.dlstilingandplumbing.chatgpt.site/images/share-12.jpg');assert.match(await n.locator('meta[property="og:title"]').getAttribute('content'),/Floating Oak/);assert.deepEqual(errors,[]);
console.log('PASS: desktop/mobile/320px; 70 looks and expanded product links; saved persistence/share; product-panel Back; shortlist round trip; correct WhatsApp recipient; guided suggestions/empty filters; per-look share metadata; no-JS fallback; main integration; 80 real-work photos preserved.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
